stages:
  - test

test:
  image: python:latest
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
  script:
    - pip install .[dev]
    - pytest --cov musiclib
    - pre-commit run --all-files
