stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  RUFF_CACHE_DIR: "$CI_PROJECT_DIR/.cache/ruff_cache"

cache:
  paths:
    - .cache/pip
    - .cache/pytest_cache
    - .cache/mypy_cache
    - .cache/ruff_cache
    - .cache/pre-commit

test:
  stage: test
  tags:
    - u61
    - docker
  image: python:3.12
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
  script:
    - pip install .[dev]
    - pytest --cov musiclib
    - pre-commit run --all-files
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
