stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  RUFF_CACHE_DIR: "$CI_PROJECT_DIR/.cache/ruff_cache"
  MYPY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/mypy_cache"

cache:
  key: $CI_PROJECT_NAME
  paths:
    - .cache/

test:
  stage: test
  tags:
    - u61
    - docker
  image: python:3.12
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
  script:
    - pip install .[dev]
    - pre-commit run --all-files
    - pytest --cov musiclib --cov-report term --cov-report xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    expire_in: 1 week
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
