stages:
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  RUFF_CACHE_DIR: "$CI_PROJECT_DIR/.cache/ruff_cache"
  MYPY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/mypy_cache"

cache:
  key: $CI_PROJECT_NAME
  paths:
    - .cache/

test:
  stage: test
  needs: []
  tags:
    - u61
    - docker
  image: python:3.12
  script:
    - pip install .[dev]
    - pytest --cov musiclib --cov-report term --cov-report xml --junitxml report.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml

lint:
  stage: test
  needs: []
  tags:
    - u61
    - docker
  image: python:3.12
  script:
    - pip install .[dev]
    - pre-commit run --all-files
