stages:
  - test

test:
  stage: test
  tags:
    - u61
  image: python:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
  script:
    - pip install .[dev]
    - pytest --cov musiclib
    - pre-commit run --all-files
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
